Update run

diff --git a/app/ovpn/run b/app/ovpn/run
--- a/app/ovpn/run
+++ b/app/ovpn/run
@@ -12,15 +12,18 @@ if [ ! -f "${TEMP_DIR}/config.ovpn" ]; then
     cp "${OPENVPN_CONFIG_FILE}" "${TEMP_DIR}/config.ovpn"
 fi
 
+TARGET_CIPHER="$(cat "${OPENVPN_CONFIG_FILE}" | grep "^cipher" | rev | cut -d ' ' -f1 | rev | tr -d ' ' | tr -d '\r' | tr -d '\n')"
+
 # Add ovpn user/pass
 if ! [ -z ${OPENVPN_USERNAME} ]; then
     # https://stackoverflow.com/questions/38869427/openvpn-on-linux-passing-username-and-password-in-command-line
-    sudo bash -c "openvpn --config ${TEMP_DIR}/config.ovpn --auth-user-pass <(echo -e "$OPENVPN_USERNAME\\\\n$OPENVPN_PASSWORD")"
+    sudo bash -c "openvpn --config ${TEMP_DIR}/config.ovpn --data-ciphers ${TARGET_CIPHER} --data-ciphers-fallback ${TARGET_CIPHER} --auth-user-pass <(echo -e "$OPENVPN_USERNAME\\\\n$OPENVPN_PASSWORD")"
 else
-    if ! openvpn --config "${TEMP_DIR}/config.ovpn"; then
-        exit_code=$?
-        echo "OpenVPN failed"
-        sleep 5
-        exit $exit_code
-    fi
+    sudo openvpn --config --data-ciphers ${TARGET_CIPHER} --data-ciphers-fallback ${TARGET_CIPHER}
+    # if ! openvpn --config "${TEMP_DIR}/config.ovpn"; then
+    #    exit_code=$?
+    #    echo "OpenVPN failed"
+    #    sleep 5
+    #    exit $exit_code
+    # fi
 fi
